// Wraps src/data/india-boundary.geojson in a JS module so the library bundles it without a JSON loader.
import { readFileSync, writeFileSync } from "node:fs";
const gj = JSON.parse(readFileSync(new URL("../src/data/india-boundary.geojson", import.meta.url), "utf8"));
const round = (v) => (Array.isArray(v) ? v.map(round) : typeof v === "number" ? +v.toFixed(6) : v);
for (const f of gj.features) f.geometry.coordinates = round(f.geometry.coordinates);
writeFileSync(new URL("../src/data/india-boundary.js", import.meta.url),
  "// Generated by scripts/embed-data.mjs from india-boundary.geojson. Do not edit by hand.\nexport default " + JSON.stringify(gj) + ";\n");
console.log("wrote src/data/india-boundary.js,", gj.features.length, "features");
