// Builds the removal polygon for the Arunachal Pradesh line from the drawn data and prints it as a
// JavaScript literal for src/config.js.
//
// The basemap's disputed line along the China side runs almost on top of the drawn line, but the
// basemap line also carries the Bhutan, Assam and Myanmar borders, which are real borders that must
// stay. So the polygon is the strip above the drawn line (the China side), with its lower edge a
// little below the line and pinched to nothing at both ends, where the drawn line meets those
// borders. Run: node scripts/make-region.mjs [margin-degrees]
import { readFileSync, writeFileSync } from "node:fs";

const MARGIN = +(process.argv[2] || 0.05);
const RAMP = 0.5; // degrees of chain over which the margin grows from 0 to full, kept long so it stays under the Bhutan and Myanmar borders
const TOP = 29.8;

const gj = JSON.parse(readFileSync(new URL("../src/data/india-boundary.geojson", import.meta.url), "utf8"));
const pieces = [];
gj.features.forEach((f) => {
  for (const c of f.geometry.type === "LineString" ? [f.geometry.coordinates] : f.geometry.coordinates)
    if (c.every((p) => p[0] > 91.4)) pieces.push(c);
});
// join the pieces end to end, starting from the westernmost free end
const key = (p) => p[0].toFixed(5) + "," + p[1].toFixed(5);
const count = new Map();
for (const c of pieces) for (const p of [c[0], c.at(-1)]) count.set(key(p), (count.get(key(p)) || 0) + 1);
const ends = [...count].filter(([, n]) => n === 1).map(([k]) => k.split(",").map(Number));
if (ends.length !== 2) throw new Error("expected one chain with two free ends, got " + ends.length);
ends.sort((a, b) => a[0] - b[0]);
let chain = [ends[0]], used = new Set();
for (;;) {
  const tip = chain.at(-1);
  const i = pieces.findIndex((c, k) => !used.has(k) && (key(c[0]) === key(tip) || key(c.at(-1)) === key(tip)));
  if (i < 0) break;
  used.add(i);
  const c = pieces[i];
  chain.push(...(key(c[0]) === key(tip) ? c.slice(1) : [...c].reverse().slice(1)));
}

// Douglas-Peucker, tolerance in degrees
function simplify(pts, tol) {
  if (pts.length < 3) return pts;
  const [a, b] = [pts[0], pts.at(-1)];
  let dmax = 0, idx = 0;
  for (let i = 1; i < pts.length - 1; i++) {
    const dx = b[0] - a[0], dy = b[1] - a[1], l2 = dx * dx + dy * dy;
    let t = l2 ? ((pts[i][0] - a[0]) * dx + (pts[i][1] - a[1]) * dy) / l2 : 0;
    t = Math.max(0, Math.min(1, t));
    const d = Math.hypot(pts[i][0] - a[0] - t * dx, pts[i][1] - a[1] - t * dy);
    if (d > dmax) { dmax = d; idx = i; }
  }
  if (dmax <= tol) return [a, b];
  return [...simplify(pts.slice(0, idx + 1), tol).slice(0, -1), ...simplify(pts.slice(idx), tol)];
}
chain = simplify(chain, 0.004);

// path length from each end, to pinch the margin
const along = [0];
for (let i = 1; i < chain.length; i++) along.push(along[i - 1] + Math.hypot(chain[i][0] - chain[i - 1][0], chain[i][1] - chain[i - 1][1]));
const total = along.at(-1);
const lower = chain.map((p, i) => {
  const m = MARGIN * Math.min(1, Math.min(along[i], total - along[i]) / RAMP);
  return [p[0], p[1] - m];
});
const r = (p) => p.map((v) => +v.toFixed(4));
const a = chain[0], b = chain.at(-1);
// walk the lower edge west to east, then up the east side and back along the top
const ring = [...lower.map(r), r([b[0] + 0.05, b[1]]), [+(b[0] + 0.05).toFixed(4), TOP], [+(a[0] - 0.05).toFixed(4), TOP], r([a[0] - 0.05, a[1] + 0.001])];
console.log(`chain ${chain.length} points, from ${r(a)} to ${r(b)}, ring ${ring.length} vertices`);
writeFileSync(
  new URL("../src/arunachal-region.js", import.meta.url),
  "// Generated by scripts/make-region.mjs from the drawn Arunachal Pradesh line. Do not edit by hand.\n" +
    "// Ring of [longitude, latitude] vertices: the strip on the China side of the drawn line.\n" +
    "export const ARUNACHAL_RING = [\n" + ring.map((p) => "  " + JSON.stringify(p) + ",").join("\n") + "\n];\n",
);
console.log("wrote src/arunachal-region.js");
