import { ARUNACHAL_RING } from "./arunachal-region.js";

// Areas where the basemap's own country lines are cut away, each a ring of [longitude, latitude]
// vertices. Only lines flagged disputed are cut, so ordinary borders (Nepal, Bhutan, Myanmar, the
// Himachal and Uttarakhand stretch of the China border) stay as the basemap draws them.
//   1. Jammu and Kashmir, Ladakh, Gilgit-Baltistan and Aksai Chin, a plain box. Its south edge sits at
//      32.3 so the basemap's own line from Spiti southwards is kept and meets the drawn line.
//   2. Arunachal Pradesh, a strip along the China side of the drawn line, generated by
//      scripts/make-region.mjs. The basemap flags the Myanmar and Bhutan borders as disputed too, and
//      those are real borders the drawn data does not repeat, so the strip is pinched to nothing at
//      both ends of the drawn line and leaves them alone.
// scripts/verify-coverage.mjs checks every free end left behind, so change these and run it.
export const REGIONS = [
  [[72.4, 32.3], [80.8, 32.3], [80.8, 37.2], [72.4, 37.2]],
  ARUNACHAL_RING,
];

// How to find the lines to remove in an OpenMapTiles-style tile. CARTO, OpenFreeMap, MapTiler,
// Stadia and others use this schema: layer "boundary", admin_level 2 for countries, a "disputed"
// flag, and "maritime" for lines at sea.
export const PROFILE = {
  layer: "boundary",
  match: (p) => Number(p.admin_level) === 2 && Number(p.maritime || 0) === 0 && Number(p.disputed) === 1,
  // style layers that draw country lines, so the module can draw the replacement the same way
  isCountryLayer: (l) =>
    l["source-layer"] === "boundary" && l.type === "line" && /admin_level["\s,\]]+2\b/.test(JSON.stringify(l.filter || "")),
};

// Bounding box [west, south, east, north] of a ring, for quick overlap tests.
export const ringBox = (ring) => {
  let w = 180, s = 90, e = -180, n = -90;
  for (const [x, y] of ring) { if (x < w) w = x; if (x > e) e = x; if (y < s) s = y; if (y > n) n = y; }
  return [w, s, e, n];
};
